In [1]:
from datetime import datetime
from datetime import date
import pytz
print(input("what is your name? "))
tz_NY = pytz.timezone('America/New_York')
now=datetime.now(tz_NY).time()
day=date.today()
print("current day: ", day)
print('current time: ', now)

what is your name? Armaan Singh
Armaan Singh
current day:  2022-04-04
current time:  17:59:06.806414


In [2]:
import pandas as pd
import numpy as np

In [3]:
print(np.__version__)

1.21.5


In [5]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [7]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr_3d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [8]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [9]:
arr_1 = np.array([1, 2, 3, 4])
print(arr_1[1])

2


In [10]:
arr_2 = np.array([1, 2, 3, 4])
print(arr_2[2] + arr_2[3])

7


In [11]:

arr_3 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr_3[0, 1])

2nd element on 1st row:  2


In [12]:
arr_4 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd row: ', arr_4[1, 4])

5th element on 2nd row:  10


In [13]:
arr_5 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr_5[0, 1, 2])

6


In [14]:
arr_6 = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr_6[1:5])

[2 3 4 5]


In [15]:
arr_7 = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr_7[-3:-1])

[5 6]


In [16]:
arr_8 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr_8[1, 1:4])

[7 8 9]


In [17]:
arr_9 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr_9[0:2, 2])

[3 8]


In [18]:
arr_10 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr_10[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [19]:
arr_11 = np.array([1, 2, 3, 4, 5])
x_1 = arr_11.copy()
arr_11[0] = 42
print(arr_11)
print(x_1)

[42  2  3  4  5]
[1 2 3 4 5]


In [20]:
arr_12 = np.array([1, 2, 3, 4, 5])
x_2 = arr_12.view()
x_2[0] = 31
print(arr_12)
print(x_2)

[31  2  3  4  5]
[31  2  3  4  5]


In [21]:
arr_13 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr_13.shape)

(2, 4)


In [22]:
arr_14 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr_14.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [23]:
arr_15 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr_15.reshape(2,4))
print("*********************")
print(arr_15.reshape(2, 4).base)

[[1 2 3 4]
 [5 6 7 8]]
*********************
[1 2 3 4 5 6 7 8]


In [25]:
arr_16 = np.array([1, 2, 3])
for x in arr_16:
  print(x)

1
2
3


In [26]:
arr_17 = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr_17:
  print(x)

[1 2 3]
[4 5 6]


In [27]:
arr_18 = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr_18:
  for y in x:
    print(y)

1
2
3
4
5
6


In [29]:
arr_19 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr_19:
  print(x)
  print("***********")

[[1 2 3]
 [4 5 6]]
***********
[[ 7  8  9]
 [10 11 12]]
***********


In [30]:
arr_20 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr_20:
  for y in x:
    print(y)
    print("***********")

[1 2 3]
***********
[4 5 6]
***********
[7 8 9]
***********
[10 11 12]
***********


In [31]:
arr21 = np.array([1, 2, 3])
arr22 = np.array([4, 5, 6])
arr_23 = np.concatenate((arr21, arr22))
print(arr_23)

[1 2 3 4 5 6]


In [33]:
arr24 = np.array([[1, 2], [3, 4]])
arr25 = np.array([[5, 6], [7, 8]])
arr_26 = np.concatenate((arr24, arr25), axis=1)
print(arr_26)

[[1 2 5 6]
 [3 4 7 8]]


In [34]:
arr27 = np.array([[1, 2], [3, 4]])
arr28 = np.array([[5, 6], [7, 8]])
arr_29 = np.concatenate((arr27, arr28), axis=0)
print(arr_29)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [35]:
arr30 = np.array([1, 2, 3])
arr31 = np.array([4, 5, 6])
arr_32 = np.hstack((arr30, arr31))
print(arr_32)

[1 2 3 4 5 6]


In [36]:
arr33 = np.array([1, 2, 3])
arr34 = np.array([4, 5, 6])
arr_35 = np.vstack((arr33, arr34))
print(arr_35)

[[1 2 3]
 [4 5 6]]


In [37]:
arr_36 = np.array([1, 2, 3, 4, 5, 4, 4])
x_3 = np.where(arr_36 == 4)
print(x_3)

(array([3, 5, 6]),)


In [38]:
arr_36 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x_4 = np.where(arr_36%2 == 0)
print(x_4)

(array([1, 3, 5, 7]),)


In [39]:
arr_37 = np.array([3, 2, 0, 1])
print(np.sort(arr_37))

[0 1 2 3]


In [40]:
arr_38 = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr_38))

['apple' 'banana' 'cherry']


In [41]:
arr_39 = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr_39))

[[2 3 4]
 [0 1 5]]


In [42]:
arr_40 = np.array([41, 42, 43, 44])
x_5 = [True, False, True, False]
newarr = arr_40[x_5]
print(newarr)

[41 43]


In [43]:
arr_41 = np.array([41, 42, 43, 44])
filter=arr_41>42
arr_41[filter]

array([43, 44])

In [44]:
arr_42 = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr_42 % 2 == 0
newarr_2 = arr_42[filter_arr]
print(filter_arr)
print(newarr_2)

[False  True False  True False  True False]
[2 4 6]
